exclude: alembic
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
        - id: mypy
          language: system
          args: [--python-version=3.10]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--config=backend/.flake8.ini]
        additional_dependencies: [
                "flake8-quotes",
                "flake8-bugbear",
                "flake8-comprehensions",
                "flake8-deprecated",
                "flake8-docstrings",
                "flake8-print",
        ]

-   repo: https://github.com/hadialqattan/pycln
    rev: v1.1.0
    hooks:
    -   id: pycln
        args: [--config=backend/pyproject.toml]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        files: "\\.(py)$"
        args: ["--settings-path=backend/pyproject.toml", "--profile", "black"]

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--config=backend/pyproject.toml]
